package com.example.geekster.project.StockManagementApplication.Model;

public enum StockType {
    ENERGY, MATERIALS, INDUSTRIALS,
    HEALTHCARE, FINANCIALS, CONSUMER_DISCRETIONARY,
    CONSUMER_STAPLES, INFORMATION_TECHNOLOGY, UTILITIES,
    COMMUNICATION_SERVICES, REAL_ESTATE, CRYPTO_CURRENCY,
    ENTERTAINMENT, TRANSPORTATION, DELIVERY,
    AUTOMOBILE, INFRASTRUCTURE, MINING
}
